// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXVymDU8Afa2L4lvIrZIyP57ogxsc5Wps',
    appId: '1:608904869263:web:66d2250caef39c5ccb87fa',
    messagingSenderId: '608904869263',
    projectId: 'skinscanv2',
    authDomain: 'skinscanv2.firebaseapp.com',
    storageBucket: 'skinscanv2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdfogfsB4roNXJLsJNfNE1s-0wcSywMAg',
    appId: '1:608904869263:android:42ca672117670ec2cb87fa',
    messagingSenderId: '608904869263',
    projectId: 'skinscanv2',
    storageBucket: 'skinscanv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW-M3FyN-s40eCN7n_o6S9j2eYO4bZAGY',
    appId: '1:608904869263:ios:55ee7279caf8de27cb87fa',
    messagingSenderId: '608904869263',
    projectId: 'skinscanv2',
    storageBucket: 'skinscanv2.appspot.com',
    iosClientId: '608904869263-uvlgqo0gn4s1525d8v2c1nv7515od9c9.apps.googleusercontent.com',
    iosBundleId: 'com.example.skinscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW-M3FyN-s40eCN7n_o6S9j2eYO4bZAGY',
    appId: '1:608904869263:ios:20d9528db8844ba4cb87fa',
    messagingSenderId: '608904869263',
    projectId: 'skinscanv2',
    storageBucket: 'skinscanv2.appspot.com',
    iosClientId: '608904869263-4fovl6c8j3sltb7cpa8pv6buier4s7kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.skinscan.RunnerTests',
  );
}
